// Builds public/index.html (one self-contained file) and public/_headers.
//
//   npm run build
//
// esbuild bundles src/main.js with its npm dependencies (jsQR) and minifies
// src/app.css; both are inlined into src/index.html. Inline code is allowed
// by SHA-256 hash, so the CSP needs no 'self' and no 'unsafe-inline': only this
// exact code can run. Anything injected later (e.g. Cloudflare's Web Analytics
// beacon, Rocket Loader, or a /cdn-cgi/ script) is blocked, and
// connect-src 'none' stops any request leaving the page.
//
// public/ is a build output (gitignored); CI and Cloudflare Pages generate it.
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const src = (f) => join(root, 'src', f)
const fail = (m) => { console.error(`build: ${m}`); process.exit(1) }

const bundle = async (entry, opts = {}) => {
  const r = await build({
    entryPoints: [src(entry)],
    bundle: true,
    minify: true,
    write: false,
    legalComments: 'inline',
    logLevel: 'warning',
    ...opts,
  })
  return r.outputFiles[0].text.trim()
}

const jsqrVersion = JSON.parse(readFileSync(join(root, 'node_modules/jsqr/package.json'), 'utf8')).version
const js = await bundle('main.js', {
  format: 'iife',
  target: ['chrome100', 'safari15'],
  banner: { js: `/*! Token Companion. Includes jsQR ${jsqrVersion} (Apache-2.0, https://github.com/cozmo/jsQR) */` },
})
const css = await bundle('app.css', { target: ['chrome100', 'safari15'] })

if (/<\/script/i.test(js)) fail('bundled JS contains </script>')
if (/<\/style/i.test(css)) fail('bundled CSS contains </style>')

let html = readFileSync(src('index.html'), 'utf8')
html = html.replace('%%CSS%%', () => css).replace('%%JS%%', () => js)

// ---- guard rails: nothing external, nothing the CSP would block ----
const markup = html.replace(/<script>[\s\S]*?<\/script>/g, '').replace(/<style>[\s\S]*?<\/style>/g, '')
if (/\son[a-z]+\s*=/i.test(markup)) fail('inline event handler attribute found')
if (/\sstyle\s*=/i.test(markup)) fail('style="" attribute found (blocked by CSP)')
for (const m of markup.matchAll(/\s(?:src|href|action|poster|srcset)\s*=\s*"([^"]*)"/gi)) {
  if (!/^(data:|#|$)/.test(m[1])) fail(`external/relative resource reference: ${m[1]}`)
}
// jsQR's licence comment and the SVG namespace are the only URLs expected.
const allowed = (u) => u === 'http://www.w3.org/2000/svg' || u.startsWith('https://github.com/cozmo/jsQR') || u.startsWith('http://www.apache.org/licenses/')
for (const m of html.matchAll(/https?:\/\/[^\s"'`)<>\\*]+/g)) {
  if (!allowed(m[0])) fail(`unexpected URL in output: ${m[0]}`)
}

// ---- CSP ----
const sha = (s) => `'sha256-${createHash('sha256').update(s, 'utf8').digest('base64')}'`
const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map((m) => sha(m[1]))
const styles = [...html.matchAll(/<style>([\s\S]*?)<\/style>/g)].map((m) => sha(m[1]))
if ((html.match(/<script/g) || []).length !== scripts.length) fail('only plain <script> blocks are supported')

const directives = [
  "default-src 'none'",
  `script-src ${scripts.join(' ')}`,
  `style-src ${styles.join(' ')}`,
  'img-src data:',          // favicon only
  "media-src 'none'",       // the camera uses srcObject, which media-src doesn't govern
  "connect-src 'none'",     // no fetch/XHR/beacon/WebSocket: nothing can phone home
  "font-src 'none'",
  "object-src 'none'",
  "worker-src 'none'",
  "child-src 'none'",
  "frame-src 'none'",
  "manifest-src 'none'",
  "base-uri 'none'",
  "form-action 'none'",
]
html = html.replace('%%CSP_META%%', directives.join('; '))
const cspHeader = [...directives, "frame-ancestors 'none'", 'upgrade-insecure-requests'].join('; ')

const headers = `# Generated by tools/build.mjs.
/*
  Content-Security-Policy: ${cspHeader}
  Cache-Control: no-cache, no-transform
  Permissions-Policy: bluetooth=(self), camera=(self), microphone=(), geolocation=(), usb=(), serial=(), hid=(), payment=(), clipboard-read=(), interest-cohort=(), browsing-topics=()
  Referrer-Policy: no-referrer
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  Cross-Origin-Embedder-Policy: require-corp
  Strict-Transport-Security: max-age=63072000; includeSubDomains
`

mkdirSync(join(root, 'public'), { recursive: true })
writeFileSync(join(root, 'public/index.html'), html)
writeFileSync(join(root, 'public/_headers'), headers)
console.log(`build: public/index.html ${(Buffer.byteLength(html) / 1024).toFixed(1)} KiB (JS ${(js.length / 1024).toFixed(1)} KiB, CSS ${(css.length / 1024).toFixed(1)} KiB)`)
